### PR TITLE
Move coveralls and istanbul from peer to dev deps

### PR DESCRIPTION
**Pull request by benadamstyles**

### CODE REVIEW

**Comment by jescalan** [comment]
Still need roots as a peer dep though, no?

**Comment by benadamstyles** [comment]
I don't know! Would you ever use this without already having roots? I don't fully understand what peerDeps are for to be totally honest.

**Comment by jescalan** [comment]
They are for plugins to another project, to specify that this project is needed alongside the plugin, and which versions its compatible with

**Comment by benadamstyles** [comment]
Ok I put it back!

**Comment by benadamstyles** [comment]
Thanks man. Any chance you could publish too?

**Comment by jescalan** [comment]
done!

**Pull request merged**
